#!/usr/bin/env python3
"""Generate src/portraits.c/.h: 16x16 (2x2 tile) avatars for the AI personas.

Each portrait uses color indices 0..3; the CGB palette chosen at draw time
(PAL_PROF/COWB/SHRK) supplies the real colors, with index 0 = felt green so
the portrait sits directly on the table with no box.

Pixel key: 0 = background (felt), 1/2/3 = the persona's three ink colors.
"""

# --- Professor: grey hair, dark glasses, mustache (1 skin, 2 dark, 3 grey) ---
PROF = [
    "0000000000000000",
    "0003333333330000",
    "0033333333333000",
    "0331133333311330",
    "0311111111111130",
    "0311111111111130",
    "0322211111222130",
    "0322211111222130",
    "0311111111111130",
    "0311111111111130",
    "0311122222211130",
    "0311111111111130",
    "0331111111111330",
    "0033111111113300",
    "0000331111330000",
    "0000003333000000",
]

# --- Cowboy: wide hat, eyes, red bandana (1 skin, 2 hat brown, 3 red) ---
COWB = [
    "0000000000000000",
    "0000022222200000",
    "0000222222220000",
    "0000222222220000",
    "0022222222222200",
    "2222222222222222",
    "2222222222222222",
    "0001111111112000",
    "0011111111111100",
    "0011221111221100",
    "0011111111111100",
    "0001111111111000",
    "0001133333331000",
    "0000133333310000",
    "0000013333100000",
    "0000001111000000",
]

# --- Shark: dorsal fin, eye, jagged teeth (1 grey, 2 dark, 3 white) ---
SHRK = [
    "0000000000000000",
    "0000000022000000",
    "0000000222000000",
    "0000002222000000",
    "0000022222200000",
    "0111122222111100",
    "1111112221111100",
    "1111111111111110",
    "1112211111111110",
    "1111111111111110",
    "1111111111111110",
    "3333333333333330",
    "0303030303030300",
    "1111111111111100",
    "0011111111110000",
    "0000000000000000",
]

PORTRAITS = [("PROF", PROF), ("COWB", COWB), ("SHRK", SHRK)]


def encode_tile(rows, x0, y0):
    """8x8 sub-tile at (x0,y0) -> 16 bytes GB 2bpp."""
    out = []
    for y in range(8):
        p0 = p1 = 0
        line = rows[y0 + y]
        for x in range(8):
            c = int(line[x0 + x])
            bit = 7 - x
            if c & 1:
                p0 |= (1 << bit)
            if c & 2:
                p1 |= (1 << bit)
        out.append(p0)
        out.append(p1)
    return out


def portrait_tiles(rows):
    """16x16 -> 4 tiles in TL, TR, BL, BR order (matches a 2x2 tile map)."""
    return [encode_tile(rows, 0, 0), encode_tile(rows, 8, 0),
            encode_tile(rows, 0, 8), encode_tile(rows, 8, 8)]


def main():
    all_tiles = []
    for _, rows in PORTRAITS:
        all_tiles.extend(portrait_tiles(rows))

    with open("src/portraits.c", "w") as f:
        f.write("/* Generated by assets/gen_portraits.py - do not edit by hand. */\n")
        f.write("#pragma bank 1\n")
        f.write("#include <gb/gb.h>\n")
        f.write('#include "portraits.h"\n\n')
        f.write("const uint8_t PORTRAIT_TILES[%d] = {\n" % (len(all_tiles) * 16))
        idx = 0
        for name, _ in PORTRAITS:
            for part in ("TL", "TR", "BL", "BR"):
                b = all_tiles[idx]
                f.write("    " + ", ".join("0x%02X" % v for v in b) +
                        ",  /* %s %s */\n" % (name, part))
                idx += 1
        f.write("};\n")
        f.write("BANKREF(PORTRAIT_TILES)\n")

    with open("src/portraits.h", "w") as f:
        f.write("#ifndef PORTRAITS_H\n#define PORTRAITS_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <gb/gb.h>\n")
        f.write('#include "carddata.h"\n\n')
        f.write("/* loaded just above the card tiles */\n")
        f.write("#define PORTRAIT_TILE_BASE ((uint8_t)(CARD_TILE_BASE + CARD_TILE_COUNT))\n")
        f.write("#define PORTRAIT_TILE_COUNT %d\n" % len(all_tiles))
        f.write("/* persona 1..3 -> first of its 4 tiles */\n")
        f.write("#define PORTRAIT_TILES_OF(persona) "
                "((uint8_t)(PORTRAIT_TILE_BASE + ((persona) - 1) * 4))\n\n")
        f.write("BANKREF_EXTERN(PORTRAIT_TILES)\n")
        f.write("extern const uint8_t PORTRAIT_TILES[%d];\n\n" % (len(all_tiles) * 16))
        f.write("#endif\n")

    print("wrote src/portraits.{c,h}: %d tiles" % len(all_tiles))


if __name__ == "__main__":
    main()
